### ISSUE TITLE
谢谢

### ISSUE THREAD

**Issue by heartacker** [shilim-developer/snippets-viewer#2]
之前有一个类似的插件，后来下架了
谢谢你这个插件。

1. 支持按照插件进行分组吗
2. 能按照语言进行排序。

**Comment by shilim-developer** [comment]
目前的设计是一级文件夹是插件名称，二级的是语言。之前有想过把所有的同语言的代码段合并的，然后想到了他插件分开写很多个同语言的文件，会不会出现重复的名称，就没有合并。

不知道你的按照插件排序的具体需求，是指插件文件夹下直接是所有语言的代码段吗？

**Comment by heartacker** [comment]
你好。你这个插件其实现在已经是按照插件进行排序了。也就是上述的 1（一级文件夹是插件名称，二级的是语言）

希望可以支持: **一级文件夹是语言，二级文件夹是插件名字**

**Comment by heartacker** [comment]
同时也希望添加一个快捷按钮等等，可以在点击之后，打开这个snippet 文件以及所在行
比如这个图中添加一个按钮。点击就可以打开这个片段文件以及所在行
![image](https://user-images.githubusercontent.com/1876302/180682623-4c17921c-0a6d-424d-970e-93637cc92489.png)
