### ISSUE TITLE
custom URL : relative path

### ISSUE THREAD

**Issue by Evileoo** [shilim-developer/snippets-viewer#4]
Hello !

I'm back with an other request 😄 

I would like to know if it was possible to add the relative path support in the CustomURL setting.

Sometimes we put a settings.json file and snippets in the .vscode folder at root of a project, but not everyone clone the project at the same path

Is it possible to add this support ?

Sorry I'm asking you a lot of things :/

**Comment by shilim-developer** [comment]
ok, i am fulfilling your requirement
