### ISSUE TITLE
relative path doesn't work in workspace

### ISSUE THREAD

**Issue by Evileoo** [shilim-developer/snippets-viewer#5]
Hello !

I tried everything and it works like a charm !

But I got one bug, when you work with a multi-folder workspace, custom snippets won't show

**Comment by shilim-developer** [comment]
> Hello !
> 
> I tried everything and it works like a charm !
> 
> But I got one bug, when you work with a multi-folder workspace, custom snippets won't show

![image](https://github.com/shilim-developer/snippets-viewer/assets/27010487/ed154c40-c462-4b1b-a363-2440b82de729)
I tested it and it works fine

**Comment by Evileoo** [comment]
Okay I found why.

When you are with "follow editor", it hides the custom snippets. It looks like the scope is ignored

**Comment by Evileoo** [comment]
Okay found the solution.

I have to put the language name is the children name in config.json

Thanks
