### ISSUE TITLE
Going on extension tab disables VSCode git colors

### ISSUE THREAD

**Issue by Evileoo** [shilim-developer/snippets-viewer#6]
Hello,

There is an issue with the extension which disable git colors until we reload VSCode, see the video below

[Vidéo 8 22 à 11.30.webm](https://github.com/user-attachments/assets/87fd1542-5b61-4aec-8caf-2138d1a412b8)

Can fix this please ?

**Comment by Evileoo** [comment]
Thanks !

**Comment by shilim-developer** [comment]
> Thanks !
You are welcome. Enjoy using it!
